### ISSUE TITLE
Crash on starting.

### ISSUE THREAD

**Issue by akvyalkov** [consulo/consulo#104]
OS: Win 8 (not 8.1).
Tryed with and without built-in jre. Also, both 32 and 64 bit. Also under administrator.

Error message:
Internal error. Please report to https://github.com/consulo/consulo/issues
```
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:177)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:233)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:361)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:523)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:505)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:169)
    ... 16 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/ide/highlighter/XmlFileType
    at org.mustbe.consulo.nunit.bundle.NUnitBundleType.setupSdkPaths(NUnitBundleType.java:164)
    at org.mustbe.consulo.bundle.DefaultPredefinedBundlesProvider.createBundles(DefaultPredefinedBundlesProvider.java:48)
    at com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader.initComponent(PredefinedBundlesLoader.java:46)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
    ... 27 more
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.highlighter.XmlFileType PluginClassLoader[org.mustbe.consulo.nunit, 633]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 31 more
```

**Comment by VISTALL** [comment]
Please drop plugins dir.

For Windows & Linux

'{UserHome}/.ConsuloData/config/plugins'
