### ISSUE TITLE
Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'

### ISSUE THREAD

**Issue by marcusrognes** [consulo/consulo#109]
I get this error after updating:
```
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:177)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:250)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:356)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:518)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:500)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:169)
    ... 16 more
Caused by: java.lang.NoSuchMethodError: org.mustbe.consulo.dotnet.module.extension.DotNetLibraryOpenCache.acquireWithNext(Ljava/lang/String;)Ledu/arizona/cs/mbel/mbel/ModuleParser;
    at org.mustbe.consulo.nunit.bundle.NUnitBundleType.getVersionString(NUnitBundleType.java:106)
    at org.mustbe.consulo.nunit.bundle.NUnitBundleType.suggestSdkName(NUnitBundleType.java:125)
    at org.mustbe.consulo.bundle.PredefinedBundlesProvider.createSdk(PredefinedBundlesProvider.java:44)
    at org.mustbe.consulo.bundle.DefaultPredefinedBundlesProvider.createBundles(DefaultPredefinedBundlesProvider.java:45)
    at com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader.initComponent(PredefinedBundlesLoader.java:46)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
    ... 27 more
```

Removing settings and plugins fixed the issue.

**Comment by marcusrognes** [comment]
Might just be some strange edge-case, i did install some other plugins that might have been conflicting with the updates.

**Comment by VISTALL** [comment]
Please update dotnet plugin, and please report at consulo-dotnet. Currently
i am waiting my airplane

Might just be some strange edge-case, i did install some other plugins that
might have been conflicting with the updates.

—
Reply to this email directly or view it on GitHub
<https://github.com/consulo/consulo/issues/109#issuecomment-119027066>.

**Comment by VISTALL** [comment]
I said not correct answer :(

I dont tested NUnit plugin, and its broken.

Please drop plugin **nunit**

For Windows & Linux: '{UserHome}/.ConsuloData/config/plugins'

On MacOS: 'Library/Application Support/ConsuloData/'

**Comment by VISTALL** [comment]
fixed: https://github.com/consulo/consulo-nunit/commit/a29d43c4d0afac56c094ef952610f7d933cc6829
