### ISSUE TITLE
Comparing branches does not work

### ISSUE THREAD

**Issue by MichaelShumenko** [consulo/consulo#118]
![comparing branches does not work](https://cloud.githubusercontent.com/assets/4786289/9156445/19969ade-3ee3-11e5-91e6-56d4a2c28587.png)

```
com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/ShowDiffAction;: com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/ShowDiffAction;
java.lang.NoSuchMethodError: com.intellij.openapi.vcs.changes.ui.ChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/ShowDiffAction;
	at git4idea.ui.branch.GitCompareBranchesLogPanel.createCenterPanel(GitCompareBranchesLogPanel.java:86)
	at git4idea.ui.branch.GitCompareBranchesLogPanel.<init>(GitCompareBranchesLogPanel.java:71)
	at git4idea.ui.branch.GitCompareBranchesDialog.createCenterPanel(GitCompareBranchesDialog.java:67)
	at com.intellij.openapi.ui.DialogWrapper.initRootPanel(DialogWrapper.java:1207)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1173)
	at git4idea.ui.branch.GitCompareBranchesDialog.<init>(GitCompareBranchesDialog.java:62)
	at git4idea.branch.GitBranchWorker.displayCompareDialog(GitBranchWorker.java:218)
	at git4idea.branch.GitBranchWorker.access$000(GitBranchWorker.java:52)
	at git4idea.branch.GitBranchWorker$2.run(GitBranchWorker.java:158)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:335)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by VISTALL** [comment]
Obsolete plugin build, need update git plugin
