### ISSUE TITLE
Error on import VisualStudio 2013 sln (Win x64)

### ISSUE THREAD

**Issue by stgolem** [consulo/consulo#120]
Error stack:

``` java
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.roots.ModuleRootManager'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:250)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.initModule(ModuleManagerImpl.java:708)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.newModule(ModuleManagerImpl.java:633)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.newModule(ModuleManagerImpl.java:611)
    at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImportBuilder.createModuleWithSingleContent(VisualStudioImportBuilder.java:270)
    at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImportBuilder.commit(VisualStudioImportBuilder.java:126)
    at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:59)
    at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:149)
    at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
    at com.intellij.ide.actions.ImportModuleAction.createFromWizard(ImportModuleAction.java:75)
    at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:70)
    at com.intellij.ide.actions.ImportModuleAction.actionPerformed(ImportModuleAction.java:60)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:248)
    at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:169)
    at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:132)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:310)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/consulo/module/extension/ui/ModuleExtensionWithSdkPanel
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClassNoExceptions(AbstractExtensionPointBean.java:48)
    at org.mustbe.consulo.module.extension.ModuleExtensionProviderEP$4.compute(ModuleExtensionProviderEP.java:116)
    at org.mustbe.consulo.module.extension.ModuleExtensionProviderEP$4.compute(ModuleExtensionProviderEP.java:113)
    at com.intellij.openapi.util.NullableLazyValue.getValue(NullableLazyValue.java:33)
    at org.mustbe.consulo.module.extension.ModuleExtensionProviderEP.createMutable(ModuleExtensionProviderEP.java:143)
    at com.intellij.openapi.roots.impl.ModuleRootLayerImpl.createMutableExtensions(ModuleRootLayerImpl.java:319)
    at com.intellij.openapi.roots.impl.ModuleRootLayerImpl.init(ModuleRootLayerImpl.java:358)
    at com.intellij.openapi.roots.impl.ModuleRootLayerImpl.<init>(ModuleRootLayerImpl.java:193)
    at com.intellij.openapi.roots.impl.RootModelImpl.initDefaultLayer(RootModelImpl.java:101)
    at com.intellij.openapi.roots.impl.RootModelImpl.<init>(RootModelImpl.java:62)
    at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.<init>(ModuleRootManagerImpl.java:58)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:559)
    ... 53 more
Caused by: java.lang.ClassNotFoundException: org.consulo.module.extension.ui.ModuleExtensionWithSdkPanel PluginClassLoader[org.consulo.google.go, 789]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 77 more
```

**Comment by VISTALL** [comment]
Please update all plugins

**Comment by stgolem** [comment]
I have first time installation 1 hour ago, or fix is already up?

**Comment by VISTALL** [comment]
You have old plugins, maybe from old installation. Please delete old plugins

https://github.com/consulo/consulo/wiki/Paths-to-system-directories

**Comment by stgolem** [comment]
Deleted whole .CosuloData reinstalled plugins
Checked for update - no update

Same error:

```
Internal error. Please report to https://github.com/consulo/consulo/issues

com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.roots.ModuleRootManager'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:250)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.initModule(ModuleManagerImpl.java:708)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.newModule(ModuleManagerImpl.java:633)
    at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.newModule(ModuleManagerImpl.java:611)
    at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImportBuilder.createModuleWithSingleContent(VisualStudioImportBuilder.java:270)
    at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImportBuilder.commit(VisualStudioImportBuilder.java:126)
    at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:59)
    at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:149)
    at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
    at com.intellij.ide.actions.ImportModuleAction.createFromWizard(ImportModuleAction.java:75)
    at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:70)
    at com.intellij.ide.actions.ImportModuleAction.actionPerformed(ImportModuleAction.java:60)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:248)
    at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:169)
    at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:132)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:310)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/consulo/module/extension/ui/ModuleExtensionWithSdkPanel
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
    at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClassNoExceptions(AbstractExtensionPointBean.java:48)
    at org.mustbe.consulo.module.extension.ModuleExtensionProviderEP$4.compute(ModuleExtensionProviderEP.java:116)
    at org.mustbe.consulo.module.extension.ModuleExtensionProviderEP$4.compute(ModuleExtensionProviderEP.java:113)
    at com.intellij.openapi.util.NullableLazyValue.getValue(NullableLazyValue.java:33)
    at org.mustbe.consulo.module.extension.ModuleExtensionProviderEP.createMutable(ModuleExtensionProviderEP.java:143)
    at com.intellij.openapi.roots.impl.ModuleRootLayerImpl.createMutableExtensions(ModuleRootLayerImpl.java:319)
    at com.intellij.openapi.roots.impl.ModuleRootLayerImpl.init(ModuleRootLayerImpl.java:358)
    at com.intellij.openapi.roots.impl.ModuleRootLayerImpl.<init>(ModuleRootLayerImpl.java:193)
    at com.intellij.openapi.roots.impl.RootModelImpl.initDefaultLayer(RootModelImpl.java:101)
    at com.intellij.openapi.roots.impl.RootModelImpl.<init>(RootModelImpl.java:62)
    at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.<init>(ModuleRootManagerImpl.java:58)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:559)
    ... 53 more
Caused by: java.lang.ClassNotFoundException: org.consulo.module.extension.ui.ModuleExtensionWithSdkPanel PluginClassLoader[org.consulo.google.go, 789]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 77 more
```

**Comment by stgolem** [comment]
Same error if i try to create Empty project

**Comment by VISTALL** [comment]
Please show plugin manager page from settings

**Comment by VISTALL** [comment]
Please fully delete .ConsuloData directory and Consulo - i tested, and all good (you have old plugins, and new consulo build)

**Comment by stgolem** [comment]
Ok. I have removed all Consulo files and get fresh download.
Last time i was using x64 on Windows so this error remains same.
Now i got x32 - import was successfull, but there is other bugs i post them in separate issue later
