### ISSUE TITLE
Save settings failed on OSX

### ISSUE THREAD

**Issue by strobe** [consulo/consulo#122]
I got this with latest version (#1060, jdk 1.8.0_45):

```
[  11770]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
com.intellij.openapi.components.StateStorageException: java.io.IOException: /Users/evgeniy/Library/Preferences/ConsuloData/options not found
	at com.intellij.openapi.components.impl.stores.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.java:243)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.executeSave(ComponentStoreImpl.java:132)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.doSave(ComponentStoreImpl.java:125)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.save(ComponentStoreImpl.java:119)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl._saveSettings(ApplicationImpl.java:1394)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1405)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:799)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$700(ApplicationImpl.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:780)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:786)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:734)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:729)
	at com.intellij.ide.actions.ExitAction.actionPerformed(ExitAction.java:31)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: /Users/evgeniy/Library/Preferences/ConsuloData/options not found
	at com.intellij.openapi.components.impl.stores.StorageUtil.getOrCreateVirtualFile(StorageUtil.java:214)
	at com.intellij.openapi.components.impl.stores.StorageUtil.writeFile(StorageUtil.java:142)
	at com.intellij.openapi.components.impl.stores.FileBasedStorage$FileSaveSession.doSave(FileBasedStorage.java:149)
	at com.intellij.openapi.components.impl.stores.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.java:239)
	... 25 more
[  11844]   WARN - api.vfs.impl.local.FileWatcher - Watcher terminated with exit code 0 
logout
```
 ("/Users/evgeniy/Library/Preferences/ConsuloData/options" is exist)

**Comment by VISTALL** [comment]
Hi. Strange
I will check it in near future

**Comment by VISTALL** [comment]
For now - i am trying to stable master after some merge from upstream. 

Sorry for that

**Comment by strobe** [comment]
Also found different thing but also looks related to this issue:

if I've open directory selection dialog by pressing import project button at startup dialog then any directories will disappear  then I clicked on any directory or on gray arrow icons. 

see my video record: [file_dialog_issue_on_osx.mp4](https://dl.dropboxusercontent.com/u/11846276/Consulo_bug_reports/file_dialog_issue_on_osx.mp4)

**Comment by VISTALL** [comment]
its the same issue

**Comment by VISTALL** [comment]
Try File->Invalidate Caches

**Comment by VISTALL** [comment]
Try last build pls

**Comment by strobe** [comment]
yes, latest build #1080 fixed this issue for me (I did clear install with full removing of following directories:
```
~/Library/Preferences/ConsuloData
~/Library/Application Support/ConsuloData
~/Library/Logs/ConsuloData
```

Thanks

**Comment by VISTALL** [comment]
Okey - thanks, and sorry for problems
