### ISSUE TITLE
Icon cannot be found in '/resources/icons/xmlProperties.png'

### ISSUE THREAD

**Issue by vlasas** [consulo/consulo#123]
Build #1086, Linux.
Ubuntu 15.04 x64
Event Log is always red, because of:
Icon cannot be found in '/resources/icons/xmlProperties.png', aClass='class icons.PropertiesIcons'
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:148)
	at icons.PropertiesIcons.load(PropertiesIcons.java:13)
	at icons.PropertiesIcons.<clinit>(PropertiesIcons.java:16)
	at com.intellij.lang.properties.xml.XmlPropertiesIconDescriptorUpdater.updateIcon(XmlPropertiesIconDescriptorUpdater.java:33)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mustbe.consulo.extensions.CompositeExtensionPointName$MyInvocationHandler.invokeVoidMethod(CompositeExtensionPointName.java:175)
	at org.mustbe.consulo.extensions.CompositeExtensionPointName$MyInvocationHandler.invoke(CompositeExtensionPointName.java:92)
	at com.sun.proxy.$Proxy86.updateIcon(Unknown Source)
	at com.intellij.ide.IconDescriptorUpdaters.getIconWithoutCache(IconDescriptorUpdaters.java:43)
	at com.intellij.ide.IconDescriptorUpdaters.getIcon(IconDescriptorUpdaters.java:33)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$1.run(AbstractPsiBasedNode.java:145)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:892)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:132)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:582)
	at com.intellij.ide.util.treeView.AbstractTreeUi$21.run(AbstractTreeUi.java:938)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:934)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:886)
	at com.intellij.ide.util.treeView.AbstractTreeUi.collectNodesToInsert(AbstractTreeUi.java:2250)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4400(AbstractTreeUi.java:60)
	at com.intellij.ide.util.treeView.AbstractTreeUi$29.run(AbstractTreeUi.java:1393)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:69)
	at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:225)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
	at com.intellij.openapi.util.ActionCallback.notify(ActionCallback.java:153)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33.run(AbstractTreeUi.java:1777)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2085)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5800(AbstractTreeUi.java:60)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.run(AbstractTreeUi.java:1977)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:439)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2180)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37.run(AbstractTreeUi.java:1972)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by VISTALL** [comment]
Thanks - fixed
