### ISSUE TITLE
Exception on Importing Unity Project

### ISSUE THREAD

**Issue by mneubertinnogames** [consulo/consulo#124]
Hi,

using Mac, OS X 10.10.5.
Unity 5.1.2

Get exception below when I try to import my unity project. I used Monodevelop before, which is the reason that there are .sln files inside the unity project directory.
This seems consulo to try to use VisualStudio importer which is not working for directories:

As a work around I will try to delete those Monodevelop file generated by the Unity Editor and also try disabling the visual studio importer. It would be awesome if you could fix this issue soon.

java.io.FileNotFoundException: /Users/matthiasneubert/dev/mygame (Is a directory): java.io.FileNotFoundException: /Users/matthiasneubert/dev/mygame (Is a directory)
java.lang.RuntimeException: java.io.FileNotFoundException: /Users/matthiasneubert/dev/mygame (Is a directory)
at com.google.common.base.Throwables.propagate(Throwables.java:160)
at org.mustbe.consulo.visualStudio.util.VisualStudioSolutionParser.parse(VisualStudioSolutionParser.java:74)
at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImportBuilder.loadItems(VisualStudioImportBuilder.java:297)
at org.mustbe.consulo.visualStudio.importProvider.ui.VisualStudioSetupTargetStep.<init>(VisualStudioSetupTargetStep.java:53)
at org.mustbe.consulo.visualStudio.importProvider.VisualStudioImporterProvider.createSteps(VisualStudioImporterProvider.java:49)
at com.intellij.projectImport.ProjectImportProvider.addSteps(ProjectImportProvider.java:90)
at com.intellij.ide.util.newProjectWizard.modes.ImportMode.createSteps(ImportMode.java:73)
at com.intellij.ide.util.newProjectWizard.modes.WizardMode.getSteps(WizardMode.java:47)
at com.intellij.ide.util.newProjectWizard.AddModuleWizard.initModuleWizard(AddModuleWizard.java:138)
at com.intellij.ide.util.newProjectWizard.AddModuleWizard.<init>(AddModuleWizard.java:94)
at com.intellij.ide.actions.ImportModuleAction.createImportWizard(ImportModuleAction.java:184)
at com.intellij.ide.actions.ImportModuleAction.selectFileAndCreateWizard(ImportModuleAction.java:139)
at com.intellij.ide.actions.ImportModuleAction.selectFileAndCreateWizard(ImportModuleAction.java:118)
at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:64)
at com.intellij.ide.actions.ImportModuleAction.actionPerformed(ImportModuleAction.java:60)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:248)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:263)
at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:233)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:106)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:754)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:702)
at java.awt.EventQueue$3.run(EventQueue.java:696)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:724)
at java.awt.EventQueue$4.run(EventQueue.java:722)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: /Users/matthiasneubert/dev/mygame (Is a directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at com.google.common.io.Files$FileByteSource.openStream(Files.java:124)
at com.google.common.io.Files$FileByteSource.openStream(Files.java:114)
at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:287)
at com.google.common.io.CharStreams$3.getInput(CharStreams.java:508)
at com.google.common.io.CharStreams$3.getInput(CharStreams.java:505)
at com.google.common.io.CharStreams.readLines(CharStreams.java:319)
at com.google.common.io.Files.readLines(Files.java:690)
at org.mustbe.consulo.visualStudio.util.VisualStudioSolutionParser.parse(VisualStudioSolutionParser.java:63)
... 50 more

**Comment by mneubertinnogames** [comment]
Disabling Visual Studio Imported Plugin brought me one step further. I was able to select Unity Importing. After the new imported consulo project opened I got another exception in .net core:

org/consulo/module/extension/ModuleExtensionProviderEP: org/consulo/module/extension/ModuleExtensionProviderEP
java.lang.NoClassDefFoundError: org/consulo/module/extension/ModuleExtensionProviderEP
at org.mustbe.consulo.dotnet.module.roots.DotNetLibraryOrderEntryTypeProvider.getCellAppearance(DotNetLibraryOrderEntryTypeProvider.java:79)
at org.mustbe.consulo.dotnet.module.roots.DotNetLibraryOrderEntryTypeProvider.getCellAppearance(DotNetLibraryOrderEntryTypeProvider.java:36)
at com.intellij.ide.projectView.impl.nodes.NamedLibraryElementNode.update(NamedLibraryElementNode.java:117)
at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
at com.intellij.ide.projectView.ProjectViewNode.validate(ProjectViewNode.java:264)
at com.intellij.ide.projectView.BaseProjectTreeBuilder.validateNode(BaseProjectTreeBuilder.java:417)
at com.intellij.ide.util.treeView.AbstractTreeUi.isValid(AbstractTreeUi.java:3327)
at com.intellij.ide.util.treeView.AbstractTreeUi.loadElementsFromStructure(AbstractTreeUi.java:2204)
at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildrenNow(AbstractTreeUi.java:1361)
at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1283)
at com.intellij.ide.util.treeView.AbstractTreeUi.access$3000(AbstractTreeUi.java:60)
at com.intellij.ide.util.treeView.AbstractTreeUi$25$1.run(AbstractTreeUi.java:1176)
at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
at com.intellij.ide.util.treeView.AbstractTreeUi.access$2400(AbstractTreeUi.java:60)
at com.intellij.ide.util.treeView.AbstractTreeUi$25.run(AbstractTreeUi.java:1173)
at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1168)
at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodesToInsert(AbstractTreeUi.java:1670)
at com.intellij.ide.util.treeView.AbstractTreeUi.access$4200(AbstractTreeUi.java:60)
at com.intellij.ide.util.treeView.AbstractTreeUi$29$2.run(AbstractTreeUi.java:1398)
at com.intellij.ide.util.treeView.AbstractTreeUi$29$2.run(AbstractTreeUi.java:1394)
at com.intellij.openapi.util.AsyncResult$1.run(AsyncResult.java:74)
at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
at com.intellij.openapi.util.AsyncResult.doWhenDone(AsyncResult.java:71)
at com.intellij.ide.util.treeView.AbstractTreeUi$29.run(AbstractTreeUi.java:1393)
at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:69)
at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:225)
at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
at com.intellij.openapi.util.ActionCallback.notify(ActionCallback.java:153)
at com.intellij.ide.util.treeView.AbstractTreeUi$33.run(AbstractTreeUi.java:1777)
at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2085)
at com.intellij.ide.util.treeView.AbstractTreeUi.access$5800(AbstractTreeUi.java:60)
at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.run(AbstractTreeUi.java:1977)
at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:439)
at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2180)
at com.intellij.ide.util.treeView.AbstractTreeUi$37.run(AbstractTreeUi.java:1972)
at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:702)
at java.awt.EventQueue$3.run(EventQueue.java:696)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.consulo.module.extension.ModuleExtensionProviderEP PluginClassLoader[org.mustbe.consulo.dotnet.core, 1791]
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 63 more

**Comment by mneubertinnogames** [comment]
May be due to the disabling of the visual studio plugin I also get a class def not found exception: (if this is relevant)

org/consulo/vfs/backgroundTask/BackgroundTaskByVfsChangeProvider$ByFileType: org/consulo/vfs/backgroundTask/BackgroundTaskByVfsChangeProvider$ByFileType
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: org/consulo/vfs/backgroundTask/BackgroundTaskByVfsChangeProvider$ByFileType
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:111)
at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:48)
at org.mustbe.consulo.vfs.backgroundTask.BackgroundTaskByVfsChangeProviders.getProviders(BackgroundTaskByVfsChangeProviders.java:34)
at org.mustbe.consulo.vfs.backgroundTask.ui.widget.BackgroundTaskWidget.update(BackgroundTaskWidget.java:92)
at org.mustbe.consulo.vfs.backgroundTask.ui.widget.BackgroundTaskWidget.selectionChanged(BackgroundTaskWidget.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:294)
at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
at com.sun.proxy.$Proxy96.selectionChanged(Unknown Source)
at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$17.run(FileEditorManagerImpl.java:1599)
at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14$1.run(FileEditorManagerImpl.java:1033)
at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:672)
at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:656)
at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:626)
at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
at com.intellij.openapi.wm.impl.FocusManagerImpl$11.run(FocusManagerImpl.java:522)
at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2070)
at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:500)
at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:495)
at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:64)
at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$ToolWindowFocusWatcher.focusedComponentChanged(ToolWindowManagerImpl.java:2332)
at com.intellij.openapi.wm.FocusWatcher._setFocused(FocusWatcher.java:154)
at com.intellij.openapi.wm.FocusWatcher.setFocusedComponentImpl(FocusWatcher.java:149)
at com.intellij.openapi.wm.FocusWatcher.focusGained(FocusWatcher.java:95)
at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:220)
at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
at java.awt.Component.processFocusEvent(Component.java:6414)
at java.awt.Component.processEvent(Component.java:6281)
at java.awt.Container.processEvent(Container.java:2234)
at java.awt.Component.dispatchEventImpl(Component.java:4881)
at java.awt.Container.dispatchEventImpl(Container.java:2292)
at java.awt.Component.dispatchEvent(Component.java:4703)
at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:986)
at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:610)
at java.awt.Component.dispatchEventImpl(Component.java:4752)
at java.awt.Container.dispatchEventImpl(Container.java:2292)
at java.awt.Component.dispatchEvent(Component.java:4703)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:702)
at java.awt.EventQueue$3.run(EventQueue.java:696)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:724)
at java.awt.EventQueue$4.run(EventQueue.java:722)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: org/consulo/vfs/backgroundTask/BackgroundTaskByVfsChangeProvider$ByFileType
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:156)
at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:152)
at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:128)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:156)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
... 71 more
Caused by: java.lang.ClassNotFoundException: org.consulo.vfs.backgroundTask.BackgroundTaskByVfsChangeProvider$ByFileType PluginClassLoader[JFlex Support, 1302]
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 86 more
Caused by:

java.lang.NoClassDefFoundError: org/consulo/vfs/backgroundTask/BackgroundTaskByVfsChangeProvider$ByFileType
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:156)
at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:152)
at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:128)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:156)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:111)
at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:48)
at org.mustbe.consulo.vfs.backgroundTask.BackgroundTaskByVfsChangeProviders.getProviders(BackgroundTaskByVfsChangeProviders.java:34)
at org.mustbe.consulo.vfs.backgroundTask.ui.widget.BackgroundTaskWidget.update(BackgroundTaskWidget.java:92)
at org.mustbe.consulo.vfs.backgroundTask.ui.widget.BackgroundTaskWidget.selectionChanged(BackgroundTaskWidget.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:294)
at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
at com.sun.proxy.$Proxy96.selectionChanged(Unknown Source)
at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$17.run(FileEditorManagerImpl.java:1599)
at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14$1.run(FileEditorManagerImpl.java:1033)
at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:672)
at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:656)
at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:626)
at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
at com.intellij.openapi.wm.impl.FocusManagerImpl$11.run(FocusManagerImpl.java:522)
at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2070)
at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:500)
at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:495)
at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:64)
at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$ToolWindowFocusWatcher.focusedComponentChanged(ToolWindowManagerImpl.java:2332)
at com.intellij.openapi.wm.FocusWatcher._setFocused(FocusWatcher.java:154)
at com.intellij.openapi.wm.FocusWatcher.setFocusedComponentImpl(FocusWatcher.java:149)
at com.intellij.openapi.wm.FocusWatcher.focusGained(FocusWatcher.java:95)
at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:220)
at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
at java.awt.Component.processFocusEvent(Component.java:6414)
at java.awt.Component.processEvent(Component.java:6281)
at java.awt.Container.processEvent(Container.java:2234)
at java.awt.Component.dispatchEventImpl(Component.java:4881)
at java.awt.Container.dispatchEventImpl(Container.java:2292)
at java.awt.Component.dispatchEvent(Component.java:4703)
at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:986)
at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:610)
at java.awt.Component.dispatchEventImpl(Component.java:4752)
at java.awt.Container.dispatchEventImpl(Container.java:2292)
at java.awt.Component.dispatchEvent(Component.java:4703)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:702)
at java.awt.EventQueue$3.run(EventQueue.java:696)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:724)
at java.awt.EventQueue$4.run(EventQueue.java:722)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:647)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.consulo.vfs.backgroundTask.BackgroundTaskByVfsChangeProvider$ByFileType PluginClassLoader[JFlex Support, 1302]
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 86 more

**Comment by VISTALL** [comment]
Please update Consuli. You have too old consulo build with newest plugins.
Be care - VS import is not priority and you can have problems. If u want
use with unity - pease use direct import from root unity project dir
7 сент. 2015 г. 12:55 пользователь "Matthias Neubert" <
notifications@github.com> написал:

**Comment by mneubertinnogames** [comment]
Hi,

I downloaded Consulo Today, using the link provided here. I suppose its the recent Consulo Version containing the recent Plugin versions. Afaik consulo cannot update the plugins using the intelliJ plugin update mechanism, so I don't have any idea how to update the plugins.
Since I don't use visual studio and only want to use it for unity development I suppose I can uninstall the VS Importer plugin, right? Or are there any dependencies for the C# or unity support to the VS Plugin?

**Comment by VISTALL** [comment]
Yeah you can disable VS importer

**Comment by mneubertinnogames** [comment]
Hi,

Plugin Updating now worked and I don't get any exceptions anymore. I uninstalled the VS Importer.
Now I have the problem that I cannot create a Run/Build Configuration for it, because the Module is NULL. (Error running testMacAny: Module is null) 

See attached my current settings / state of the project
![asembly_extensions](https://cloud.githubusercontent.com/assets/8258691/9716201/cdabc1f8-5567-11e5-975b-86c8da9e4e66.png)
![asembly_dependencies](https://cloud.githubusercontent.com/assets/8258691/9716203/cdc9b078-5567-11e5-9b40-37eb38649529.png)
![my_module_project_structure](https://cloud.githubusercontent.com/assets/8258691/9716204/cdc9c388-5567-11e5-94b3-0b452d3a30d6.png)
![external_libs](https://cloud.githubusercontent.com/assets/8258691/9716202/cdc893f0-5567-11e5-9d84-155e52ddbcea.png)
![build_config_without_module](https://cloud.githubusercontent.com/assets/8258691/9716205/cdca8048-5567-11e5-8639-0f7c630f5966.png)

**Comment by VISTALL** [comment]
Running from consulo is currenly disabled, due Unity limitation, u can only
attach to editor or app. Attah button placed near Debug

**Comment by mneubertinnogames** [comment]
Ahh, good to know! Debugging a running Editor instance works fine. 
Question: since running from consulo don't work, is it at least possible to set up to compile/build the code from consulo? If yes, how does setup this?

**Comment by VISTALL** [comment]
Currenly its not possible, unity dont provide good plugin api(or any api),
and for now i dont have time make via hardcode variant, Sorry

**Comment by VISTALL** [comment]
I will close this issue. If you wanna talk about unity please use consulo-unity3d repository. And you will see related issues
