### ISSUE TITLE
vim emulator plugin doesn't work correctly.

### ISSUE THREAD

**Issue by RayRiver** [consulo/consulo#139]
The plugin doesn't work correctly.
I cannot use it.

**Comment by VISTALL** [comment]
You it inside IntelliJ IDEA? And whats wrong

**Comment by VISTALL** [comment]
I think i found problem

**Comment by VISTALL** [comment]
Try after few hours

**Comment by cc-lam** [comment]
Consulo 1.0 Build 1240
MacBook Pro OSX 10.11.1

I was sooooo happy when I found out about Consulo ....
and soooo disappointed that the vim plugin didn't work (deal breaker as far as I'm concerned) ...

After installing the plugin, restarting the application crashes Consulo.
After the crash, Consulo does not crash again when re-opening manually but the vim plugin is broken: I can enter edit mode but I cannot exit edit mode (the esc key does not seem to be recognized).

I think this issue should be re-opened.

**Comment by VISTALL** [comment]
If you have crash - you can attach **idea.log** file (from log directory https://github.com/consulo/consulo/wiki/Paths-to-system-directories) or

hs_err_pid<pid>.log file from bin directory

**Comment by 3xp0n3nt** [comment]
Please re-open this issue. The vim plugin is broken. I can press 'i' to get to insert mode, but pressing escape does not return to normal mode. There is no crash.

Consulo 1.0 Build 1246
MacBook Pro OS X 10.10.5 (Yosemite)

**Comment by 3xp0n3nt** [comment]
When I disable the vim emulator, I get a crash:

```
Exception in plugin Vim Emulator.

Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:141)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.setCurrentCommandName(CoreCommandProcessor.java:221)
	at com.intellij.codeInsight.editorActions.TypedHandler.type(TypedHandler.java:246)
	at com.intellij.codeInsight.editorActions.TypedHandler.access$100(TypedHandler.java:63)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:211)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:343)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:423)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:153)
	at com.intellij.codeInsight.template.impl.editorActions.SpaceHandler.execute(SpaceHandler.java:48)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:90)
	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.java:66)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:134)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1198)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5585)
	at com.intellij.openapi.editor.impl.EditorImpl$12.keyTyped(EditorImpl.java:1023)
	at java.awt.Component.processKeyEvent(Component.java:6471)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2828)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:618)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1300)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertWriteAccess(DocumentImpl.java:574)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:433)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:131)
	at com.intellij.openapi.editor.EditorModificationUtil.access$000(EditorModificationUtil.java:35)
	at com.intellij.openapi.editor.EditorModificationUtil$2.perform(EditorModificationUtil.java:349)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:343)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:423)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.openapi.editor.EditorModificationUtil.typeInStringAtCaretHonorMultipleCarets(EditorModificationUtil.java:346)
	at com.intellij.openapi.editor.EditorModificationUtil.typeInStringAtCaretHonorMultipleCarets(EditorModificationUtil.java:337)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler$1.run(LookupTypedHandler.java:120)
	at com.intellij.codeInsight.lookup.impl.LookupOffsets.performGuardedChange(LookupOffsets.java:128)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.performGuardedChange(LookupImpl.java:604)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.beforeCharTyped(LookupTypedHandler.java:117)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:85)
	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.java:66)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:134)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1198)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5585)
	at com.intellij.openapi.editor.impl.EditorImpl$12.keyTyped(EditorImpl.java:1023)
	at java.awt.Component.processKeyEvent(Component.java:6471)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2828)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:618)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
http://napile.myjetbrains.com/youtrack/issue/CEP-1482

**Comment by VISTALL** [comment]
Try build #441
