### ISSUE TITLE
Can't configure task server

### ISSUE THREAD

**Issue by likerRr** [consulo/consulo#148]
I try to add Trello as task server in order to create\read tasks directly from Consulo. When I test connection I always get `Unknown error`

![clip2net_151115183734](https://cloud.githubusercontent.com/assets/1290558/11169426/8992709c-8bc8-11e5-928c-84d69d2579a8.png)

Error details:
![clip2net_151115183916](https://cloud.githubusercontent.com/assets/1290558/11169433/d610039e-8bc8-11e5-9395-572b96c73f5c.png)

Error details (text):
```
null
java.lang.NullPointerException
	at com.intellij.tasks.impl.httpclient.NewBaseRepositoryImpl.getHttpClient(NewBaseRepositoryImpl.java:69)
	at com.intellij.tasks.impl.httpclient.NewBaseRepositoryImpl$HttpTestConnection.test(NewBaseRepositoryImpl.java:197)
	at com.intellij.tasks.impl.httpclient.NewBaseRepositoryImpl$HttpTestConnection.doTest(NewBaseRepositoryImpl.java:182)
	at com.intellij.tasks.TaskRepository$CancellableConnection.call(TaskRepository.java:343)
	at com.intellij.tasks.TaskRepository$CancellableConnection.call(TaskRepository.java:334)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:428)
	at com.intellij.openapi.application.impl.ApplicationImpl$10.call(ApplicationImpl.java:441)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by VISTALL** [comment]
Thanks - reproduced

**Comment by VISTALL** [comment]
Hi you need update consulo after some time. It was platform issue.

Thanks
