### ISSUE TITLE
Expression Evaluator, Watches and Stack list

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#161]
verision 1.0 1280 build.
C# Unity Project
Watches tab.
xmlDocument.ChildNodes.
(or anything In Watches is = empty and throw error)
dough in Variables tab I can see value of xmlDocument.ChildNodes:

Exception have null message
java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
	at java.util.ArrayDeque.remove(ArrayDeque.java:447)
	at org.mustbe.consulo.csharp.ide.debugger.CSharpEvaluateContext.popValue(CSharpEvaluateContext.java:69)
	at org.mustbe.consulo.csharp.ide.debugger.CSharpDebuggerProvider.evaluate(CSharpDebuggerProvider.java:115)
	at org.mustbe.consulo.dotnet.debugger.DotNetStackFrame$2.evaluate(DotNetStackFrame.java:163)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.addWatchExpression(WatchesRootNode.java:145)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl.addWatchExpression(XWatchesViewImpl.java:287)
	at com.intellij.xdebugger.impl.frame.WatchInplaceEditor.doOKAction(WatchInplaceEditor.java:81)
	at com.intellij.xdebugger.impl.ui.tree.TreeInplaceEditor$6.actionPerformed(TreeInplaceEditor.java:179)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at com.intellij.ui.EditorTextField.processKeyBinding(EditorTextField.java:699)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2943)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:618)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by VISTALL** [comment]
Hi. Please provide more info about Watches.

About missed items. They dont missed - they not implemented, due its **language** feature, and IntelliJ dont provide any C# impl.

Please dont merge all issues into one. 

For C# use this repository https://github.com/consulo/consulo-csharp


Thanks

**Comment by winalex** [comment]
I separate issue. Sorry. Bit frustrated. I'm programmer I know how difficult is to do what you do. As I understand the Generate and Extract are some kind of templates/macros probably not difficult to adjust from Java to C#.

**Comment by VISTALL** [comment]
Nope, its not template. Need write code for it(not a few lines). I need single issue for all missed actions.

**Comment by winalex** [comment]
I'll provide to you what ever you need.
<img width="1395" alt="screen shot 2016-03-07 at 11 08 02 am" src="https://cloud.githubusercontent.com/assets/689092/13566512/3d974208-e456-11e5-9ed0-4f2625393d9d.png">

**Comment by winalex** [comment]
<img width="1410" alt="screen shot 2016-03-07 at 11 09 19 am" src="https://cloud.githubusercontent.com/assets/689092/13566528/5020fd2e-e456-11e5-86c2-3c59516567e4.png">

**Comment by VISTALL** [comment]
I repeated. 

http://klikr.org/3b202f6f4877fec8fde77dcb2c68.png

**Comment by winalex** [comment]
see xmlDocument.ChildNodes

**Comment by VISTALL** [comment]
I found a problem - now watchers works. But - not fully(because it not implemented).

I closed another issue, except Exception. I will try to repeat it

You can update C# plugin after 30 min maybe
