### ISSUE TITLE
Expanding Variable in Variables tab Debug Mode

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#162]
Mac Osx 1.0. build 1280 Unity C# project
XMLDocument variable. Expanding Tree cause this error:
```csharp
Wrong count of arguments: Wrong count of arguments
java.lang.IllegalArgumentException: Wrong count of arguments
	at mono.debugger.MethodMirror.invoke(MethodMirror.java:120)
	at mono.debugger.PropertyMirror.value(PropertyMirror.java:95)
	at org.mustbe.consulo.dotnet.debugger.nodes.DotNetFieldOrPropertyMirrorNode.getValueOfVariableImpl(DotNetFieldOrPropertyMirrorNode.java:109)
	at org.mustbe.consulo.dotnet.debugger.nodes.DotNetAbstractVariableMirrorNode$2.fun(DotNetAbstractVariableMirrorNode.java:191)
	at org.mustbe.consulo.dotnet.debugger.nodes.DotNetAbstractVariableMirrorNode$2.fun(DotNetAbstractVariableMirrorNode.java:186)
	at org.mustbe.consulo.dotnet.debugger.nodes.DotNetAbstractVariableMirrorNode.invoke(DotNetAbstractVariableMirrorNode.java:233)
	at org.mustbe.consulo.dotnet.debugger.nodes.DotNetAbstractVariableMirrorNode.getValueOfVariableSafe(DotNetAbstractVariableMirrorNode.java:185)
	at org.mustbe.consulo.dotnet.debugger.nodes.DotNetAbstractVariableMirrorNode.computePresentation(DotNetAbstractVariableMirrorNode.java:304)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:74)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode$1.run(XValueContainerNode.java:95)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:82)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:79)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:644)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by VISTALL** [comment]
O_o


Can you say full type of variable?

**Comment by winalex** [comment]
System.Xml.XmlDocument

**Comment by VISTALL** [comment]
Cant repeat for now

**Comment by winalex** [comment]
Will the video help?

**Comment by VISTALL** [comment]
No i will try to repeat it :)

**Comment by VISTALL** [comment]
Looks like i repeated it

**Comment by winalex** [comment]
Cool thx

**Comment by VISTALL** [comment]
Fixed. It was bug in debugger library.

You can update plugins in one hour

**Comment by winalex** [comment]
Thx

**Comment by VISTALL** [comment]
About code generation & refactoring, please create new issues here https://github.com/consulo/consulo-csharp/issues

**Comment by winalex** [comment]
Created!. Generate and Extract C# option support suggestion #358
