### ISSUE TITLE
IDE doesn't like my file :)

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#169]
When Open IDE doesn't like file:

Please delete after check.

```
Error while indexing /Projects/FiniteStateMachineSubmission/Assets/1_WinxProduction/ws/winx/unity/UnityObservable.cs
To reindex this file IDEA has to be restarted
java.lang.StackOverflowError
	at com.intellij.lang.impl.PsiBuilderImpl.whitespaceOrComment(PsiBuilderImpl.java:808)
	at com.intellij.lang.impl.PsiBuilderImpl.skipWhitespace(PsiBuilderImpl.java:765)
	at com.intellij.lang.impl.PsiBuilderImpl.eof(PsiBuilderImpl.java:837)
	at com.intellij.lang.impl.PsiBuilderImpl.calcTokenType(PsiBuilderImpl.java:678)
	at com.intellij.lang.impl.PsiBuilderImpl.getTokenType(PsiBuilderImpl.java:668)
	at com.intellij.lang.impl.PsiBuilderAdapter.getTokenType(PsiBuilderAdapter.java:56)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:193)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
```

**Comment by VISTALL** [comment]
Looks like bug in parser, i will check after LINQ issue. Link deleted

Thanks

**Comment by VISTALL** [comment]
Moved

**Comment by VISTALL** [comment]
Cant reproduce. After plugins update - try to open again this file, and report me here https://github.com/consulo/consulo-csharp/issues/364

**Comment by winalex** [comment]
I did. 3 errors.
11:34:15 AM StackOverflowError
            Error while indexing /Projects/FiniteStateMachineSubmission/Assets/1_WinxProduction/ws/winx/unity/UnityObservable.cs
            To reindex this file IDEA has to be restarted
11:34:17 AM StackOverflowError: null
11:34:18 AM StackOverflowError: null


Error while indexing /Projects/FiniteStateMachineSubmission/Assets/1_WinxProduction/ws/winx/unity/UnityObservable.cs
To reindex this file IDEA has to be restarted
java.lang.StackOverflowError
	at com.intellij.lang.impl.PsiBuilderImpl.calcTokenType(PsiBuilderImpl.java:678)
	at com.intellij.lang.impl.PsiBuilderImpl.getTokenType(PsiBuilderImpl.java:668)
	at com.intellij.lang.impl.PsiBuilderAdapter.getTokenType(PsiBuilderAdapter.java:56)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:193)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277)
	at org.mustbe.consulo.csharp.lang.parser.CSharpBuilderWrapper.getTokenType(CSharpBuilderWrapper.java:277

**Comment by VISTALL** [comment]
![](http://klikr.org/69c19c85cec3e28549afe8534fd6.png)

**Comment by VISTALL** [comment]
Looks like i reproduced

**Comment by VISTALL** [comment]
fixed

**Comment by winalex** [comment]
own you box of beer or votka. what u prefer?

**Comment by VISTALL** [comment]
Pepsi :)

**Comment by VISTALL** [comment]
Use please C# repository for C# bugs
