### ISSUE TITLE
Cyclic component initialization

### ISSUE THREAD

**Issue by catena2w** [consulo/consulo#182]
# Please read contributing guide first

- IDE build number: idea-IC-143.1184.17
- Java version: 1.8.0_77
- OS name and version: Linux Mint 17.3 Rosa

On startup I always see:

[ 514058]  ERROR - ij.components.ComponentManager - Cyclic component initialization: class com.intellij.ide.ui.LafManager [Plugin: com.intellij] 
com.intellij.diagnostic.PluginException: Cyclic component initialization: class com.intellij.ide.ui.LafManager [Plugin: com.intellij]
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:184)
	at com.intellij.ide.ui.LafManager.getInstance(LafManager.java:29)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$1.onCurrentSchemeChanged(EditorColorsManagerImpl.java:111)
	at com.intellij.configurationStore.SchemeManagerImpl.setCurrent(SchemeManagerImpl.kt:804)
	at com.intellij.openapi.options.SchemesManager.setCurrent(SchemesManager.java:61)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.setGlobalScheme(EditorColorsManagerImpl.java:254)
	at com.intellij.ide.ui.laf.darcula.DarculaInstaller.install(DarculaInstaller.java:48)
	at com.intellij.ide.ui.laf.LafManagerImpl.initComponent(LafManagerImpl.java:227)

**Comment by VISTALL** [comment]
?
