### ISSUE TITLE
Local history Broken

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo#197]
- IDE build number:1351
- Java version:1.7.0_101
- OS name and version:  Linux Mint 17.3 Rosa

This is second time this happens. Has happen with older version before(don't remember which ). 

Local history is broken(version:5,current timestamp:Jun 28, 2016 2:08:05 PM,storage timestamp:Jun 20, 2016 8:45:41 PM,vfs timestamp:Jun 20, 2016 8:45:41 PM)
null: Corrupted records: storageLength=280 recordsLength=248 recordSize=32
java.io.IOException: Corrupted records: storageLength=280 recordsLength=248 recordSize=32
    at com.intellij.util.io.storage.AbstractRecordsTable.getRecordsCount(AbstractRecordsTable.java:105)
    at com.intellij.util.io.storage.AbstractRecordsTable.createNewRecord(AbstractRecordsTable.java:89)
    at com.intellij.history.core.LocalHistoryStorage.createNextRecord(LocalHistoryStorage.java:105)
    at com.intellij.history.core.ChangeListStorageImpl.writeNextSet(ChangeListStorageImpl.java:211)
    at com.intellij.history.core.ChangeList.doEndChangeSet(ChangeList.java:100)
    at com.intellij.history.core.ChangeList.endChangeSet(ChangeList.java:88)
    at com.intellij.history.core.LocalHistoryFacade.endChangeSet(LocalHistoryFacade.java:55)
    at com.intellij.history.core.LocalHistoryFacade.addChange(LocalHistoryFacade.java:97)
    at com.intellij.history.core.LocalHistoryFacade.contentChanged(LocalHistoryFacade.java:66)
    at com.intellij.history.integration.LocalHistoryEventDispatcher.beforeContentsChange(LocalHistoryEventDispatcher.java:109)
    at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
    at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
    at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
    at com.sun.proxy.$Proxy15.beforeContentsChange(Unknown Source)
    at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireBefore(BulkVirtualFileListenerAdapter.java:102)
    at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.before(BulkVirtualFileListenerAdapter.java:47)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy17.before(Unknown Source)
    at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$5.close(PersistentFSImpl.java:631)
    at com.intellij.openapi.components.impl.stores.StorageUtil.writeFile(StorageUtil.java:152)
    at com.intellij.openapi.components.impl.stores.FileBasedStorage$FileSaveSession.doSave(FileBasedStorage.java:149)
    at com.intellij.openapi.components.impl.stores.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.java:239)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.executeSave(ComponentStoreImpl.java:132)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.doSave(ComponentStoreImpl.java:125)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.save(ComponentStoreImpl.java:119)
    at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
    at com.intellij.openapi.application.impl.ApplicationImpl._saveSettings(ApplicationImpl.java:1364)
    at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1375)
    at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:157)
    at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:141)
    at com.intellij.ide.SaveAndSyncHandlerImpl$4$1.run(SaveAndSyncHandlerImpl.java:109)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
    at com.intellij.ide.SaveAndSyncHandlerImpl$4.onFrameDeactivated(SaveAndSyncHandlerImpl.java:105)
    at com.intellij.ide.FrameStateManagerImpl.fireDeactivationEvent(FrameStateManagerImpl.java:104)
    at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:34)
    at com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:74)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:892)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:406)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by VISTALL** [comment]
Hi. Currently i am busy at work. This exception - i think will fix, when finish merge with IDEA (idk when i finish it, its very big issue)

**Comment by VISTALL** [comment]
I think is obsolete for 2 version
