### ISSUE TITLE
Startup  fatal error

### ISSUE THREAD

**Issue by yanmasharski** [consulo/consulo#207]
# Please read contributing guide first. Please read and remove this header before issue submit

- IDE build number: 1384
- Java version: 1.8.0_101
- OS name and version: Windows 10 x64

Error on startup.

Internal error. Please report to https://github.com/consulo/consulo/issues

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:131)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:250)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:355)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:517)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:117)
    ... 16 more
Caused by: java.lang.AbstractMethodError: com.sun.jna.Structure.getFieldOrder()Ljava/util/List;
    at com.sun.jna.Structure.fieldOrder(Structure.java:884)
    at com.sun.jna.Structure.getFields(Structure.java:910)
    at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
    at com.sun.jna.Structure.calculateSize(Structure.java:982)
    at com.sun.jna.Structure.calculateSize(Structure.java:949)
    at com.sun.jna.Structure.useMemory(Structure.java:312)
    at com.sun.jna.Structure.<init>(Structure.java:181)
    at com.sun.jna.Structure.<init>(Structure.java:172)
    at com.sun.jna.Structure.<init>(Structure.java:168)
    at org.mustbe.consulo.unity3d.bundle.WindowsVersionHelper$VS_FIXEDFILEINFO.<init>(WindowsVersionHelper.java:66)
    at org.mustbe.consulo.unity3d.bundle.WindowsVersionHelper.getVersion(WindowsVersionHelper.java:84)
    at org.mustbe.consulo.unity3d.bundle.Unity3dBundleType.getVersionString(Unity3dBundleType.java:130)
    at org.mustbe.consulo.unity3d.bundle.Unity3dBundleType.suggestSdkName(Unity3dBundleType.java:191)
    at org.mustbe.consulo.bundle.PredefinedBundlesProvider.createSdk(PredefinedBundlesProvider.java:44)
    at org.mustbe.consulo.bundle.DefaultPredefinedBundlesProvider.createBundles(DefaultPredefinedBundlesProvider.java:45)
    at com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader.initComponent(PredefinedBundlesLoader.java:52)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
    ... 27 more

**Comment by VISTALL** [comment]
? Actual?

**Comment by VISTALL** [comment]
Drop **unity3d** from plugin dir (you can find path here https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

And install Unity3d plugin again.

**Comment by yanmasharski** [comment]
Thank you!
I've cleared Consulo plugins directory and everything works fine.

пн, 8 авг. 2016 г. в 12:45, Valeriy Semenchuk <notifications@github.com>:
