### ISSUE TITLE
vim plugin prevents consulo from starting up

### ISSUE THREAD

**Issue by NanaDada** [consulo/consulo#220]
- IDE build number: 1395
- Java version: The build including the JRE
- OS name and version: OSX 10.11.6 - El-Crappy-tan

Thank you very much for supplying consulo! It's awesome to have IntelliJ for Unity! Unfortunately the vim plugin prevents consulo from starting up. Below is the stack trace. It would be nice if you could take a look at it, as vim is one of the most efficient editors for people who develop lots of code.
Thank you.

Plugin 'org.mustbe.consulo.vim' failed to initialize and will be disabled.  Please restart Consulo.

java.lang.AssertionError
    at com.maddyhome.idea.vim.group.KeyGroup.addNode(KeyGroup.java:350)
    at com.maddyhome.idea.vim.group.KeyGroup.registerAction(KeyGroup.java:338)
    at com.maddyhome.idea.vim.group.KeyGroup.registerAction(KeyGroup.java:321)
    at com.maddyhome.idea.vim.group.KeyGroup.registerAction(KeyGroup.java:276)
    at com.maddyhome.idea.vim.RegisterActions.registerNormalModeActions(RegisterActions.java:491)
    at com.maddyhome.idea.vim.RegisterActions.registerActions(RegisterActions.java:44)
    at com.maddyhome.idea.vim.VimPlugin.initComponent(VimPlugin.java:150)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:355)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:517)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:117)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by VISTALL** [comment]
Hi. Its duplicate https://github.com/consulo/consulo-vim/issues/1

I don't have much time for this plugin. For now

**Comment by VISTALL** [comment]
I merged from upstream. You can test it, after few hours

**Comment by NanaDada** [comment]
Aweseome! Thank you very much! Just one question: How can consulo be build from source (on osx)?

**Comment by VISTALL** [comment]
Some information you can found here https://github.com/consulo/consulo/wiki/Plugin-Development-Starter-Guide

Consulo 1.0 sources you can found [here ](https://github.com/consulo/consulo/tree/1.0) (do not use master branch is next iteration and not compatible with 1.0)
