### ISSUE TITLE
Consulo crashes when opening potentially corrupt .ConsuloData folder

### ISSUE THREAD

**Issue by seuribe** [consulo/consulo#228]
# Please read contributing guide first. Please read and remove this header before issue submit
- IDE build number: 
  Consulo 1.0 / 1401
- Java version:
  java version "1.8.0_51"
  Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
  Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
- OS name and version: 
  Microsoft Windows [Version 10.0.10586](64 bit)

Issue description. In most cases need provide reproduce example.

Get this message with exception on start:

Computer crashes. I restart and attempt to run Consulo, get exception copied below.
I suspect the configuration files in ~/.ConsuloData was corrupted, as after removing/renaming it I could start Consulo and re-import the project.

Message shown:
"Internal error. Please report to https://github.com/consulo/consulo/issues

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:131)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:250)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:355)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:517)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:117)
    ... 16 more
Caused by: java.lang.AbstractMethodError: com.sun.jna.Structure.getFieldOrder()Ljava/util/List;
    at com.sun.jna.Structure.fieldOrder(Structure.java:884)
    at com.sun.jna.Structure.getFields(Structure.java:910)
    at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
    at com.sun.jna.Structure.calculateSize(Structure.java:982)
    at com.sun.jna.Structure.calculateSize(Structure.java:949)
    at com.sun.jna.Structure.useMemory(Structure.java:312)
    at com.sun.jna.Structure.<init>(Structure.java:181)
    at com.sun.jna.Structure.<init>(Structure.java:172)
    at com.sun.jna.Structure.<init>(Structure.java:168)
    at org.mustbe.consulo.unity3d.bundle.WindowsVersionHelper$VS_FIXEDFILEINFO.<init>(WindowsVersionHelper.java:66)
    at org.mustbe.consulo.unity3d.bundle.WindowsVersionHelper.getVersion(WindowsVersionHelper.java:84)
    at org.mustbe.consulo.unity3d.bundle.Unity3dBundleType.getVersionString(Unity3dBundleType.java:130)
    at org.mustbe.consulo.unity3d.bundle.Unity3dBundleType.suggestSdkName(Unity3dBundleType.java:191)
    at org.mustbe.consulo.bundle.PredefinedBundlesProvider.createSdk(PredefinedBundlesProvider.java:44)
    at org.mustbe.consulo.bundle.DefaultPredefinedBundlesProvider.createBundles(DefaultPredefinedBundlesProvider.java:45)
    at com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader.initComponent(PredefinedBundlesLoader.java:52)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
    ... 27 more
"

**Comment by VISTALL** [comment]
Hi. Sorry for that (it was my mistake i break backward compatibility).

Go to **Plugin Dir** (about https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

Drop unity3d directory(plugin).

And after start Consulo - goto Preferences->General->Plugins->Browse Plugins. And install Unity3D plugin.

Sorry.

Regards Valeriy
