### ISSUE TITLE
 I get an error when starting the IDE (java.lang.RuntimeException)

### ISSUE THREAD

**Issue by vyach-vasiliev** [consulo/consulo#233]
# I get an error when starting the IDE (java.lang.RuntimeException)

- IDE build number - `1.0.0.1` _(latest version today 03.11.16)_:
- Java version - `jre1.8.0_74`:
- OS Windows, 8.1 SL RUS: 

Loading on a black background comes to the end, but it does not opened app window and throws an error
I get an error with the default settings in file `*.vmoptions`
launch any of these files `consulo.exe` or `consulo64.exe` causes this error:

	java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
		at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:131)
		at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
		at java.awt.event.InvocationEvent.dispatch(Unknown Source)
		at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
		at java.awt.EventQueue.access$500(Unknown Source)
		at java.awt.EventQueue$3.run(Unknown Source)
		at java.awt.EventQueue$3.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
		at java.awt.EventQueue.dispatchEvent(Unknown Source)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
		at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
		at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
		at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
		at java.awt.EventDispatchThread.run(Unknown Source)
	Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader'
		at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:250)
		at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:40)
		at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
		at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
		at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
		at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
		at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
		at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:355)
		at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
		at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
		at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
		at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:517)
		at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
		at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:117)
		... 16 more
	Caused by: java.lang.AbstractMethodError: com.sun.jna.Structure.getFieldOrder()Ljava/util/List;
		at com.sun.jna.Structure.fieldOrder(Structure.java:884)
		at com.sun.jna.Structure.getFields(Structure.java:910)
		at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
		at com.sun.jna.Structure.calculateSize(Structure.java:982)
		at com.sun.jna.Structure.calculateSize(Structure.java:949)
		at com.sun.jna.Structure.useMemory(Structure.java:312)
		at com.sun.jna.Structure.<init>(Structure.java:181)
		at com.sun.jna.Structure.<init>(Structure.java:172)
		at com.sun.jna.Structure.<init>(Structure.java:168)
		at org.mustbe.consulo.unity3d.bundle.WindowsVersionHelper$VS_FIXEDFILEINFO.<init>(WindowsVersionHelper.java:66)
		at org.mustbe.consulo.unity3d.bundle.WindowsVersionHelper.getVersion(WindowsVersionHelper.java:84)
		at org.mustbe.consulo.unity3d.bundle.Unity3dBundleType.getVersionString(Unity3dBundleType.java:130)
		at org.mustbe.consulo.unity3d.bundle.Unity3dBundleType.suggestSdkName(Unity3dBundleType.java:191)
		at org.mustbe.consulo.bundle.PredefinedBundlesProvider.createSdk(PredefinedBundlesProvider.java:44)
		at org.mustbe.consulo.bundle.DefaultPredefinedBundlesProvider.createBundles(DefaultPredefinedBundlesProvider.java:45)
		at com.intellij.openapi.projectRoots.impl.PredefinedBundlesLoader.initComponent(PredefinedBundlesLoader.java:52)
		at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
		... 27 more

**Comment by VISTALL** [comment]
Hi.  You need drop unity3d directory in plugin dir path u can found here https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

And install Unity3D pluguin again

**Comment by vyach-vasiliev** [comment]
Oh yes, it worked! 😃 Thank you very much, it's just an amazing work! 👍✨

**Comment by VISTALL** [comment]
Nice. Sorry for this bug
