### ISSUE TITLE
Internal error on startup

### ISSUE THREAD

**Issue by Epicface92** [consulo/consulo#244]
After using the in beta auto-update I got this...

EDIT: removed log info because the exception wasn't shown very well.

Internal error. Please report to https://github.com/consulo/consulo/issues

java.lang.RuntimeException: java.lang.NullPointerException
    at com.intellij.idea.ApplicationStarter.run(ApplicationStarter.java:139)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
    at com.intellij.openapi.actionSystem.ex.ComboBoxButton.getFont(ComboBoxButton.java:241)
    at javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:206)
    at javax.swing.plaf.basic.BasicButtonUI.installDefaults(BasicButtonUI.java:111)
    at javax.swing.plaf.basic.BasicButtonUI.installUI(BasicButtonUI.java:88)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at com.intellij.openapi.actionSystem.ex.ComboBoxButton.updateUI(ComboBoxButton.java:171)
    at javax.swing.AbstractButton.init(AbstractButton.java:2176)
    at javax.swing.JButton.<init>(JButton.java:137)
    at javax.swing.JButton.<init>(JButton.java:91)
    at com.intellij.openapi.actionSystem.ex.ComboBoxButton.<init>(ComboBoxButton.java:54)
    at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createComboBoxButton(ComboBoxAction.java:61)
    at com.intellij.execution.actions.RunConfigurationsComboBoxAction.createCustomComponent(RunConfigurationsComboBoxAction.java:134)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getCustomComponent(ActionToolbarImpl.java:349)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.fillToolBar(ActionToolbarImpl.java:305)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:949)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:64)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:173)
    at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:191)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:649)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:630)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:600)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$9(FocusManagerImpl.java:482)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2429)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:462)
    at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:108)
    at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:93)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.setMiniMode(ActionToolbarImpl.java:1337)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:189)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:152)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:208)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:203)
    at com.intellij.openapi.wm.impl.IdeRootPane.createToolbar(IdeRootPane.java:222)
    at com.intellij.openapi.wm.impl.IdeRootPane.updateToolbar(IdeRootPane.java:195)
    at com.intellij.openapi.wm.impl.IdeRootPane.<init>(IdeRootPane.java:96)
    at com.intellij.openapi.wm.impl.IdeFrameImpl.createRootPane(IdeFrameImpl.java:173)
    at com.intellij.openapi.wm.impl.IdeFrameImpl.<init>(IdeFrameImpl.java:97)
    at com.intellij.openapi.wm.impl.WindowManagerImpl.showFrame(WindowManagerImpl.java:519)
    at com.intellij.idea.starter.DefaultApplicationPostStarter.main(DefaultApplicationPostStarter.java:122)
    at com.intellij.idea.ApplicationStarter$1.run(ApplicationStarter.java:131)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
    at com.intellij.idea.ApplicationStarter.run(ApplicationStarter.java:128)
    ... 16 more

(Sorry if I didn't put the error in a spoiler!)

It's been preventing me from using the bleeding-edge version and I had to switch back to build 1401

- IDE build number: 1538
- Java version: jdk1.8.0_101
- OS name and version: Mac OS X El Captain 10.11.6

**Comment by VISTALL** [comment]
Hi. Thanks for this issue. I will check

**Comment by VISTALL** [comment]
Hi. Wait few hours - and download new build (and call check for updates - for update plugins).

It's my mistake - I'm sorry.

Thanks

**Comment by Epicface92** [comment]
Looks like you fixed the issue, the ide doesn't bring up a error anymore. I'll keep you updated if it decides to crash on startup again.
