### ISSUE TITLE
DLLs can't get decompiled correctly.

### ISSUE THREAD

**Issue by burakkurkcu** [consulo/consulo#246]
- IDE build number: 1556
- Java version: 1.8.0_76-release
- OS name and version: MacOSX Sierra 10.12.2 (16C67)

After getting into 2.0 release, this error happens and auto complete gets broken too often. Also I'm not always getting this error with Unity's internal DLLs, sometimes it's 3rd party Unity plugin DLLs I use in project like DoTween's. 

I am trying to get over it by invalidating caches from file menu. Sometimes it works, but it's frustrating to be honest :(

Error log and screenshots below:

```
05:03	IndexOutOfBoundsException: File '/Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll' cant decompiled correctly please create issue with this file: Index: 0

05:03	IndexOutOfBoundsException: File '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll' cant decompiled correctly please create issue with this file: Index: 0
```
<img width="1340" alt="screen shot 2017-01-15 at 06 15 02" src="https://cloud.githubusercontent.com/assets/5931039/21960006/c15fc54c-dae1-11e6-84f5-10b456218cf2.png">

<img width="563" alt="screen shot 2017-01-15 at 06 15 19" src="https://cloud.githubusercontent.com/assets/5931039/21960007/c16605c4-dae1-11e6-92ed-204c394de890.png">

**Comment by VISTALL** [comment]
It's very rare exception for me  (don't known reason). Try "Invalidate cache" (File -> Invalidate cache)

Thanks

**Comment by VISTALL** [comment]
Oh. 

Will try to repeat. Thanks

**Comment by VISTALL** [comment]
Can you try this fix? 

1. Shutdown Consulo
2. Goto `~/Library/Application Support/Consulo/consulo.dotnet/lib`
3. Replace dotnet-asm.jar by this file (make backup old file): https://drive.google.com/file/d/0BwdC25ghEUn_Y0JaNzFqcGphWjg/view?usp=sharing 
4. Start Consulo, call Invalidate - and try

Revert file if no success

**Comment by burakkurkcu** [comment]
Tried twice, first time there was no errors on log but autocomplete was broken still. Then tried again to invalide and restart this time popped an error and autocomplete is broken again. No chance :( 

`18:34	IndexOutOfBoundsException: File '/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll' cant decompiled correctly please create issue with this file: Index: 0`

**Comment by VISTALL** [comment]
It's with fix ?

**Comment by burakkurkcu** [comment]
Yes.

**Comment by VISTALL** [comment]
Sorry for bug. Working on it

**Comment by VISTALL** [comment]
Another try (replace dotnet-misl-decompiler.jar by this https://drive.google.com/open?id=0BwdC25ghEUn_RXRid3VocExXb3c)

**Comment by burakkurkcu** [comment]
I just replaced dotnet-misl-decompiler.jar on after fresh install. file -> invalidated and problem still persists.

```
Invalid generic index for type ThreadSafeDictionary`2, index: 0
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:125)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilSharedBuilder.typeToString(MsilSharedBuilder.java:588)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilSharedBuilder.typeToString(MsilSharedBuilder.java:571)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilSharedBuilder.toStringFromDefRefSpec(MsilSharedBuilder.java:660)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilTypeBuilder$1.fun(MsilTypeBuilder.java:115)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilTypeBuilder$1.fun(MsilTypeBuilder.java:111)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilSharedBuilder.join(MsilSharedBuilder.java:634)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilTypeBuilder.processTypeDef(MsilTypeBuilder.java:110)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilTypeBuilder.processTypeDef(MsilTypeBuilder.java:132)
	at consulo.internal.dotnet.msil.decompiler.textBuilder.MsilStubBuilder.parseTypeDef(MsilStubBuilder.java:49)
	at consulo.internal.dotnet.msil.decompiler.file.DotNetBaseFileArchiveEntry.build(DotNetBaseFileArchiveEntry.java:66)
	at consulo.internal.dotnet.msil.decompiler.file.DotNetAbstractFileArchiveEntry$LazyValue.compute(DotNetAbstractFileArchiveEntry.java:59)
	at consulo.internal.dotnet.msil.decompiler.file.DotNetAbstractFileArchiveEntry$LazyValue.compute(DotNetAbstractFileArchiveEntry.java:24)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at consulo.internal.dotnet.msil.decompiler.file.DotNetAbstractFileArchiveEntry.createInputStream(DotNetAbstractFileArchiveEntry.java:125)
	at consulo.internal.dotnet.msil.decompiler.file.DotNetArchiveFile.getInputStream(DotNetArchiveFile.java:219)
	at com.intellij.openapi.vfs.impl.ZipHandler.contentsToByteArray(ZipHandler.java:218)
	at com.intellij.openapi.vfs.newvfs.ArchiveFileSystem.contentsToByteArray(ArchiveFileSystem.java:213)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:499)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:127)
	at com.intellij.ide.caches.FileContent.getBytes(FileContent.java:48)
	at com.intellij.openapi.project.FileContentQueue.doLoadContent(FileContentQueue.java:144)
	at com.intellij.openapi.project.FileContentQueue.loadContent(FileContentQueue.java:119)
	at com.intellij.openapi.project.FileContentQueue.loadNextContent(FileContentQueue.java:103)
	at com.intellij.openapi.project.FileContentQueue.access$100(FileContentQueue.java:41)
	at com.intellij.openapi.project.FileContentQueue$1.run(FileContentQueue.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by VISTALL** [comment]
It's my debug. Code is red ? (as i understand)

**Comment by burakkurkcu** [comment]
It's a red error log, but besides error log autocomplete and everything seems to work for now. I will continue to use to see if it gets broken again.

**Comment by VISTALL** [comment]
I am closing this issue. All changes merged (available in nightly channel and later in others)
