### ISSUE TITLE
Platform not updated without admin rights, when Consulo placed under Program Files directory

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#280]
- IDE build number: 1742
- Java version: 1.8.0_112
- OS name and version: Win10

Follow up for #261.
 
Sometimes after update plugins are corrupted. They are still listed as installed:
![plugins_installed](https://user-images.githubusercontent.com/16825982/26906523-8e7c72d4-4bf6-11e7-83d8-65e3618146fe.png)

But they act as if they are totally outdated:
![plugins_corrupted](https://user-images.githubusercontent.com/16825982/26906544-b1f71db8-4bf6-11e7-8420-c75907adb096.png)

The only workaround worked for me is to go to plugin list, select each plugin and press "Uninstall plugin". After uninstalling all of them and restarting you need to reinstall plugins and it would work again.

I was able to reproduce this by pressing "Check for Update" after installing last versions of all plugins. Then Consulo still re-downloads latest updates for all plugins and corruption happens.

**Comment by unv-unv** [comment]
Just to make you know: plugin update is somehow broken now (maybe it's made intentially since you're fixing current issue, but just in case informing you):
![plugins_corrupted_2](https://user-images.githubusercontent.com/16825982/26982389-f20ecb26-4d40-11e7-9dee-bd3d642eea9b.png)

After pressing "Check for updates" and downloading updates, plugin manager said that XML, Java and JavaEE plugins are incompatible. I tried using aforementioned workaround, but option to uninstall plugin was unavailable - instead of uninstall button there was an "Update plugin" button. Pressing this button generates error.

**Comment by VISTALL** [comment]
Use always "Check for updates"

**Comment by unv-unv** [comment]
Hm. As I said, I pressed "Check for updates". And still after downloading Platform (1742->1751) Help/About shown version 1742. Then I manually deleted plugins from AppData, except for "Consulo" plugin and repeated with "Check for updates" - still 1742 after download restart. Finally I deleted "Consulo" plugin as well and repeated - still 1742.

**Comment by VISTALL** [comment]
looks like it's something new.

Use "Check for Updates". After restart (will be old version) - Help -> Show Log in Explorer, please attach *consulo.log" file.

Then - redownload Consulo.

Sorry, and thanks for patient

**Comment by unv-unv** [comment]
[consulo.zip](https://github.com/consulo/consulo/files/1064566/consulo.zip)

**Comment by VISTALL** [comment]
Hmm. Problem is. From my experience - looks like access problem. I will test it on my VMWare

```
2017-06-09 18:51:18,629 [  76937]  ERROR - Settings.impl.PluginListDialog - C:\Program Files\Consulo\platform\build1751\lib\args4j-2.33.jar (Системе не удается найти указанный путь) 
java.io.FileNotFoundException: C:\Program Files\Consulo\platform\build1751\lib\args4j-2.33.jar (Системе не удается найти указанный путь)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.install(PluginDownloader.java:158)
	at consulo.ide.updateSettings.impl.PluginListDialog.lambda$doOKAction$5(PluginListDialog.java:192)
	at com.intellij.openapi.progress.Task$Backgroundable$2.run(Task.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by unv-unv** [comment]
Redownload you mean download IDE from Download page (https://github.com/consulo/consulo/wiki/Downloads)? Windows with JRE 64bit option provides with consulo-win64-zip_1742.zip - the same version. I assume 1751 is beta and 1742 is release. I also double-checked my settings: Platform and Settings/Web Services has "Enabled updates" checked and "Channel"="beta".

**Comment by VISTALL** [comment]
Here. Beta channel

https://hub.consulo.io/#!repo/beta/consulo-win64-zip

**Comment by unv-unv** [comment]
1751 works fine, thanks.

**Comment by VISTALL** [comment]
Looks like you found another bug I will check it after my work. Strange error - my home pc on windows 10, and no problem with updates.

For some info - your UAC settings are changed?

**Comment by unv-unv** [comment]
I was lucky enough :)

Speaking about UAC settins - I think I didn't change them. But I just copied Consulo folder from zip-file into Program Files. Indeed, this may cause issues with acess rights. The next time I encounter something like this I'll check running Consulo with administrative privileges.

**Comment by VISTALL** [comment]
Nice. Thanks

**Comment by VISTALL** [comment]
I'm reproduced bug. Without admin rights you can't update Consulo under Program Files

**Comment by VISTALL** [comment]
This issue fixed (no need admin rights). But after update you need update boot files (https://github.com/consulo/consulo/wiki/Major-boot-changes) - you will notified after restart

Thanks

**Comment by VISTALL** [comment]
and updated plugin list view when plugin disabled

**Comment by unv-unv** [comment]
Update while running as Administrator seemed to work well. But just in case I've tried to update boot files.

So I've downloaded 1757 from https://hub.consulo.io/#!repo/beta/consulo-win64-zip, deleted existing C:\Program Files\Consulo and unzipped new one Consulo here.

After this I tried to run consulo64.exe and got error "'launchConsulo2' function is not found":
![launchconsulo2_not_found](https://user-images.githubusercontent.com/16825982/27148554-5fc69a3e-5149-11e7-86c2-4842c41582d1.png)

Then I tried to run consulo64.exe as Administrator and got another error "'platform' directory not found. Please visit http://consulo.io/trouble.html":
![platform_directory_not_found](https://user-images.githubusercontent.com/16825982/27148599-8a4ca19a-5149-11e7-99cd-56f6f021cab8.png)

I've double-checked - 'platform' directory exists and contains build1757 directory in it. Also, I must say, https://consulo.io/trouble.htm shows 404 error.

**Comment by VISTALL** [comment]
Please try download https://hub.consulo.io/#!repo/nightly/consulo-win64-zip **1761**

Then - call check for update

**Comment by unv-unv** [comment]
Fixed after last update (1765). Thanks.
