### ISSUE TITLE
Crash logging

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#290]
- IDE build number: 1790
- Java version: 1.8
- OS name and version: Win10

In last 2 days Consulo crashed twice when I switched to it from another process after some time of not using Consulo. I mean win process crash, not just Java error.

Is there a way to get logs or such to understand reasons? In AppData I didn't find anything relevant.

**Comment by unv-unv** [comment]
By the way, these crashes may be connected with Subversion plugin which I've started using exactly 2 days ago. At least I've installed Subversion exe files (https://sourceforge.net/projects/win32svn/) and linked Subversion plugin with them (C:\Program Files (x86)\Subversion\bin\svn.exe) on June 22.

So if after focusing Consulo after some time of unusing it starts interacting with Subversion (which seems quite likely for me), it could be a source of the problem.

**Comment by VISTALL** [comment]
Hi.

java crash logs always created near executables (in your case near consulo64.exe) - like **hs_err_pid10930.log**

**Comment by unv-unv** [comment]
I've checked there first - no logs. Probably because of no privileges writing into Program Files.

Consulo just crashed the third time. This time there was no connection to Internet. I've checked "C:\Program Files\Consulo" directory (where consulo64.exe is located) - still no logs.

Tried to run consulo64.exe as Administrator to ensure all necessary priviliges - got strange error: https://github.com/consulo/consulo/issues/291

**Comment by VISTALL** [comment]
svn.exe is not required admin rights. Idk why it's crashing

**Comment by unv-unv** [comment]
I mean writing logs into Program Files may require admin rights.

**Comment by VISTALL** [comment]
Oh.Maybe you are right. Move Consulo to another directory - and install svn plugin. I will read how change directory for crash reports

**Comment by unv-unv** [comment]
Update. Crashes only happen in case Consulo is under Program Files. Crashes happen occasionally. Once per hour or more rarely. Crashes only happen when I switch to Consulo after some period of inactivity.

So maybe there's some process happening only on Consulo window activation and trying to save something (history or such) into program directory without requesting proper access rights?

**Comment by VISTALL** [comment]
Can you add option to consulo64.vmoptions

(change only path to file)

>> -XX:ErrorFile=/var/log/java/hs_err_pid%p.log

And then try to find log after crash

Thanks

**Comment by unv-unv** [comment]
After specifying this property no crashes happened for more than a day. Seems that such a logging into Program Files by default may be the initial case of crashing.

By the way, I see many similar errors in Event Log of IDE when editing JSP:
```
In file: file://C:/Projects/DB-150/db150.jsp: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.intellij.psi.controlFlow.DefUseUtil$RefsDefs$1Inner.traverse(DefUseUtil.java:526)
	at com.intellij.psi.controlFlow.DefUseUtil$RefsDefs.get(DefUseUtil.java:572)
	at com.intellij.psi.controlFlow.DefUseUtil$RefsDefs.access$200(DefUseUtil.java:467)
	at com.intellij.psi.controlFlow.DefUseUtil.getDefs(DefUseUtil.java:397)
	at com.intellij.psi.controlFlow.DefUseUtil.getDefs(DefUseUtil.java:330)
	at com.siyeh.ig.psiutils.DeclarationSearchUtils.findDefinition(DeclarationSearchUtils.java:131)
	at com.intellij.psi.impl.source.resolve.reference.impl.JavaReflectionReferenceUtil.findVariableDefinition(JavaReflectionReferenceUtil.java:252)
	at com.intellij.psi.impl.source.resolve.reference.impl.JavaReflectionReferenceUtil.getReflectiveType(JavaReflectionReferenceUtil.java:193)
	at com.intellij.psi.impl.source.resolve.reference.impl.JavaReflectionReferenceUtil.getReflectiveClass(JavaReflectionReferenceUtil.java:215)
	at com.intellij.psi.impl.source.resolve.reference.impl.JavaLangClassMemberReference.getPsiClass(JavaLangClassMemberReference.java:119)
	at com.intellij.psi.impl.source.resolve.reference.impl.JavaLangClassMemberReference.resolve(JavaLangClassMemberReference.java:76)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitLiteralExpression(HighlightVisitorImpl.java:1141)
	at com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl.accept(PsiLiteralExpressionImpl.java:354)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:190)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:367)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:326)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$2(HighlightVisitorImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:459)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:220)
	at consulo.javaee.jsp.codeInsight.daemon.analysis.JspJavaHighlightVisitorImpl.analyze(JspJavaHighlightVisitorImpl.java:34)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:911)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:85)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:72)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1080)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:264)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

And then after some time in Event Log:
```
	com.intellij.diagnostic.MessagePool$TooManyErrorsException: Too many IDE fatal errors. Monitoring stopped.
```

So I assume there may be some background error logging.

**Comment by VISTALL** [comment]
Can you attach some example for reproduce? (wanna find reason of this exception)

**Comment by unv-unv** [comment]
I've sent you example by email.

**Comment by VISTALL** [comment]
exception fixed

**Comment by unv-unv** [comment]
I confirm - after las update exception disappeared. Thanks!

**Comment by unv-unv** [comment]
Alas, even after Psi exception have gone, crashes haven't been fixed. I've removed -XX:ErrorFile (with link to public folder) from consulo64.exe.vmoptions and after some hours Consulo crashed again (it never crashed when -XX:ErrorFile with link to publick folder was present).

**Comment by VISTALL** [comment]
Strange
