### ISSUE TITLE
Error occurred during initialization of VM java.lang.InternalError: Could not create SecurityManager

### ISSUE THREAD

**Issue by coderhasib** [consulo/consulo#531]
- IDE build number:c onsulo.dist.linux64_3355.tar.gz
- Java version: openjdk version "17.0.8" 2023-07-18
- OS name and version: Zorin OS 16.3

Issue description. In most cases need provide reproduce example.

```
hasibul@hasibul-S551LN:/media/hasibul/WD_BACKUP/temp/Consulo$ ./consulo.sh
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: package com.apple.eawt not in java.desktop
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: package com.apple.laf not in java.desktop
WARNING: package com.apple.eawt.event not in java.desktop
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
WARNING: Unknown module: consulo.container.impl specified to --add-opens
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager
	at java.lang.System.initPhase3(java.base@17.0.8/System.java:2226)
Caused by: java.lang.ClassNotFoundException: consulo.container.impl.securityManager.impl.ConsuloSecurityManager
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@17.0.8/BuiltinClassLoader.java:641)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@17.0.8/ClassLoaders.java:188)
	at java.lang.ClassLoader.loadClass(java.base@17.0.8/ClassLoader.java:525)
	at java.lang.Class.forName0(java.base@17.0.8/Native Method)
	at java.lang.Class.forName(java.base@17.0.8/Class.java:467)
	at java.lang.System.initPhase3(java.base@17.0.8/System.java:2210)
```
i am new and  can not find proper solution yet. Please review this issue as soon as possible. Thanks.

**Comment by VISTALL** [comment]
Hello. Sorry for that error - I will check it today, and give you fix.

**Comment by VISTALL** [comment]
Please patch file Consulo/platform/build3355/bin/launcher.sh

like here

https://github.com/consulo/consulo/commit/11c107b45a11dd4942295df8a156d2c1c6ad370f

or download new build (#3358 will be available in next 3 hours)

Sorry for this problem, I forgot about this change on linux (win/mac was ok).

Thanks for reporting 🙏🏻

**Comment by Noir-Road** [comment]
Hello @VISTALL 
I patched the file from your previous response and I get the following  upon running the first time.

`noir-road@Psx:~/IDE/Consulo$ ./consulo.sh 
WARNING: package com.apple.eawt not in java.desktop
WARNING: package com.apple.laf not in java.desktop
WARNING: package com.apple.eawt.event not in java.desktop
WARNING: A command line option has enabled the Security Manager
WARNING: The Security Manager is deprecated and will be removed in a future release
Start Failed: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.desktop/java.awt.Color.<clinit>(Color.java:277)
        at consulo/consulo.ui.ex.awt.api@3-SNAPSHOT/consulo.ui.ex.awt.UIUtil.<clinit>(UIUtil.java:341)
        at consulo.desktop.awt/consulo.desktop.awt.ide.impl@3-SNAPSHOT/consulo.desktop.awt.container.impl.DesktopStartUIUtil.hackAWT(DesktopStartUIUtil.java:36)
        at consulo.desktop.awt/consulo.desktop.awt.ide.impl@3-SNAPSHOT/consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.lambda$run$1(DesktopAWTContainerStartupImpl.java:66)
        at consulo.container.api@3-SNAPSHOT/consulo.container.util.StatCollector.markWith(StatCollector.java:48)
        at consulo.desktop.awt/consulo.desktop.awt.ide.impl@3-SNAPSHOT/consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.run(DesktopAWTContainerStartupImpl.java:65)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.initAndCallStartup(Main.java:71)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.main(Main.java:51)

Also, an UI exception occurred on attempt to show above message:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.desktop/java.awt.Component.<clinit>(Component.java:624)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.showErrorDialogImpl(Main.java:82)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.access$000(Main.java:31)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main$1.showErrorDialogImpl(Main.java:36)
        at consulo.container.api@3-SNAPSHOT/consulo.container.internal.ShowError.showErrorDialog(ShowError.java:40)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.main(Main.java:54)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so [in thread "main"]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.desktop/java.awt.Color.<clinit>(Color.java:277)
        at consulo/consulo.ui.ex.awt.api@3-SNAPSHOT/consulo.ui.ex.awt.UIUtil.<clinit>(UIUtil.java:341)
        at consulo.desktop.awt/consulo.desktop.awt.ide.impl@3-SNAPSHOT/consulo.desktop.awt.container.impl.DesktopStartUIUtil.hackAWT(DesktopStartUIUtil.java:36)
        at consulo.desktop.awt/consulo.desktop.awt.ide.impl@3-SNAPSHOT/consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.lambda$run$1(DesktopAWTContainerStartupImpl.java:66)
        at consulo.container.api@3-SNAPSHOT/consulo.container.util.StatCollector.markWith(StatCollector.java:48)
        at consulo.desktop.awt/consulo.desktop.awt.ide.impl@3-SNAPSHOT/consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.run(DesktopAWTContainerStartupImpl.java:65)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.initAndCallStartup(Main.java:71)
        at consulo.desktop.awt.bootstrap@3-SNAPSHOT/consulo.desktop.awt.boot.main.Main.main(Main.java:51)
`

I'm running the following:
noir-road@Psx:~/IDE/Consulo$ java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-122.04)

Let me know if I need to provide more details :)

**Comment by VISTALL** [comment]
Hello looks like something wrong with your linux distribution and jre. It's something new.

Looks like this issues reported here https://stackoverflow.com/questions/73666286/exception-in-thread-main-java-lang-unsatisfiedlinkerror-cant-load-library

**Comment by Noir-Road** [comment]
> Hello looks like something wrong with your linux distribution and jre. It's something new.
> 
> Maybe this thread will help https://stackoverflow.com/questions/73666286/exception-in-thread-main-java-lang-unsatisfiedlinkerror-cant-load-library

You were right, for some reason some libraries were not installed properly upon installing Java 17. That fixed my problem.

Cheers
