### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by coderhasib** [consulo/consulo#533]
- IDE build number:
- Java version: 17
- OS name and version: Zorin OS

[18:13:40.337] WARN - p.DesktopImportantFolderLocker - Read timed out 
java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:961) ~[?:?]
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:343) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:595) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
	at consulo.desktop.startup.DesktopImportantFolderLocker.tryActivate(DesktopImportantFolderLocker.java:228) ~[?:?]
	at consulo.desktop.startup.DesktopImportantFolderLocker.lambda$lock$2(DesktopImportantFolderLocker.java:134) ~[?:?]
	at consulo.desktop.startup.DesktopImportantFolderLocker.underLocks(DesktopImportantFolderLocker.java:178) ~[?:?]
	at consulo.desktop.startup.DesktopImportantFolderLocker.lock(DesktopImportantFolderLocker.java:125) ~[?:?]
	at consulo.application.impl.internal.start.StartupUtil.lockSystemFolders(StartupUtil.java:130) ~[ApplicationStarter.class:?]
	at consulo.application.impl.internal.start.StartupUtil.prepareAndStart(StartupUtil.java:92) ~[ApplicationStarter.class:?]
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.start(DesktopAWTContainerStartupImpl.java:113) ~[?:?]
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.lambda$run$2(DesktopAWTContainerStartupImpl.java:73) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[18:13:40.346] ERROR - DesktopAWTContainerStartupImpl - java.lang.IllegalAccessError: class consulo.application.impl.internal.start.StartupUtil (in module consulo.application.impl) cannot access class consulo.container.internal.ShowError (in module consulo.container.api) because module consulo.container.api does not export consulo.container.internal to module consulo.application.impl 
consulo.application.impl.internal.start.StartupAbortedException: java.lang.IllegalAccessError: class consulo.application.impl.internal.start.StartupUtil (in module consulo.application.impl) cannot access class consulo.container.internal.ShowError (in module consulo.container.api) because module consulo.container.api does not export consulo.container.internal to module consulo.application.impl
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.lambda$run$2(DesktopAWTContainerStartupImpl.java:76) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalAccessError: class consulo.application.impl.internal.start.StartupUtil (in module consulo.application.impl) cannot access class consulo.container.internal.ShowError (in module consulo.container.api) because module consulo.container.api does not export consulo.container.internal to module consulo.application.impl
	at consulo.application.impl.internal.start.StartupUtil.lockSystemFolders(StartupUtil.java:154) ~[ApplicationStarter.class:?]
	at consulo.application.impl.internal.start.StartupUtil.prepareAndStart(StartupUtil.java:92) ~[ApplicationStarter.class:?]
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.start(DesktopAWTContainerStartupImpl.java:113) ~[?:?]
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.lambda$run$2(DesktopAWTContainerStartupImpl.java:73) ~[?:?]
	... 1 more
[18:13:40.369] ERROR - DesktopAWTContainerStartupImpl - Consulo 2023.8  Build #3362 
[18:13:40.369] ERROR - DesktopAWTContainerStartupImpl - JDK: 17.0.8 
[18:13:40.370] ERROR - DesktopAWTContainerStartupImpl - VM: OpenJDK 64-Bit Server VM 
[18:13:40.370] ERROR - DesktopAWTContainerStartupImpl - Vendor: Private Build 
[18:13:40.370] ERROR - DesktopAWTContainerStartupImpl - OS: Linux 

Exception: java.lang.IllegalAccessError thrown from the UncaughtExceptionHandler in thread "Consulo Main Thread"
[18:13:40.371] ERROR - DesktopAWTContainerStartupImpl - Original exception:  
java.lang.IllegalAccessError: class consulo.application.impl.internal.start.StartupUtil (in module consulo.application.impl) cannot access class consulo.container.internal.ShowError (in module consulo.container.api) because module consulo.container.api does not export consulo.container.internal to module consulo.application.impl
	at consulo.application.impl.internal.start.StartupUtil.lockSystemFolders(StartupUtil.java:154) ~[ApplicationStarter.class:?]
	at consulo.application.impl.internal.start.StartupUtil.prepareAndStart(StartupUtil.java:92) ~[ApplicationStarter.class:?]
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.start(DesktopAWTContainerStartupImpl.java:113) ~[?:?]
	at consulo.desktop.awt.container.impl.DesktopAWTContainerStartupImpl.lambda$run$2(DesktopAWTContainerStartupImpl.java:73) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

C# file not open with consulo again suddenly.

**Comment by VISTALL** [comment]
Hello. How you get this error ?

**Comment by coderhasib** [comment]
suddenly.

**Comment by VISTALL** [comment]
I think I known problem - will test and write about it (looks like there no Consulo plugin for Unity)

**Comment by VISTALL** [comment]
Again catch some problem - testing

**Comment by coderhasib** [comment]
i have tried to reinstall https://github.com/consulo/UnityEditorConsuloPlugin.git#2.6.0 and it is up to date. file not open with consulo.

**Comment by VISTALL** [comment]
There some issue inside Unity+Consulo communications - you need enable Consulo -> Socket Searching (try it)

**Comment by VISTALL** [comment]
Or 'Tools -> Create Desktop Entry' and start Consulo from it

**Comment by coderhasib** [comment]
Thanks it works again but attachted c sharp file in unity not update after change the code in consulo. show compiling screen in unity but not update code after change. after remove and reattach the file it works.
