### ISSUE TITLE
Error "Calling invokeAndWait from read-action leads to possible deadlock" when opening the maven project

### ISSUE THREAD

**Issue by serssp** [consulo/consulo#86]
test project https://github.com/serssp/test
```
2015-02-24 23:22:40,669 [ 331465]  ERROR - plication.impl.ApplicationImpl - Calling invokeAndWait from read-action leads to possible deadlock. 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:678)
	at org.jetbrains.idea.maven.utils.MavenUtil.invokeAndWait(MavenUtil.java:170)
	at org.jetbrains.idea.maven.utils.MavenUtil.invokeAndWait(MavenUtil.java:153)
	at org.jetbrains.idea.maven.utils.MavenMergingUpdateQueue.makeModalAware(MavenMergingUpdateQueue.java:179)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.initWorkers(MavenProjectsManager.java:301)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.doInit(MavenProjectsManager.java:217)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.initMavenized(MavenProjectsManager.java:197)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.access$100(MavenProjectsManager.java:96)
	at org.jetbrains.idea.maven.project.MavenProjectsManager$1.run(MavenProjectsManager.java:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:308)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:300)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$100(StartupManagerImpl.java:51)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:900)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivities(StartupManagerImpl.java:112)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$8.run(ProjectManagerImpl.java:457)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:409)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:618)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:421)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:193)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:282)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl$11$1.run(ApplicationImpl.java:645)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:415)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:51)

```

**Comment by VISTALL** [comment]
Moved https://github.com/consulo/consulo-maven/issues/2

**Comment by VISTALL** [comment]
Thanks

**Comment by VISTALL** [comment]
Fixed
