### ISSUE TITLE
Internal error. Please report to https://github.com/consulo/consulo/issues

### ISSUE THREAD

**Issue by anton-280** [consulo/consulo#87]
Internal error. Please report to https://github.com/consulo/consulo/issues

java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.util.indexing.FileBasedIndex'
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:177)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.util.indexing.FileBasedIndex'
    at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:233)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:364)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:526)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:508)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:169)
    ... 16 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/fileTypes/StdFileTypes
    at com.intellij.psi.tree.xml.IXmlElementType.<init>(IXmlElementType.java:27)
    at com.intellij.psi.xml.XmlElementType.<clinit>(XmlElementType.java:32)
    at com.intellij.lang.html.HTMLParserDefinition.getFileNodeType(HTMLParserDefinition.java:49)
    at com.intellij.psi.stubs.CumulativeStubVersion.getCumulativeVersion(CumulativeStubVersion.java:37)
    at com.intellij.psi.stubs.StubUpdatingIndex.getVersion(StubUpdatingIndex.java:208)
    at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:369)
    at com.intellij.util.indexing.FileBasedIndexImpl.initExtensions(FileBasedIndexImpl.java:279)
    at com.intellij.util.indexing.FileBasedIndexImpl.initComponent(FileBasedIndexImpl.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
    ... 27 more
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.fileTypes.StdFileTypes PluginClassLoader[com.intellij.xml, 701]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more

**Comment by VISTALL** [comment]
Please drop plugins dir.

For Windows & Linux

{UserHome}/config/plugins

**Comment by VISTALL** [comment]
On MacOS

 'Library/Application Support/ConsuloData/'

**Comment by VISTALL** [comment]
any news?

**Comment by anton-280** [comment]
Consulo dont start

**Comment by anton-280** [comment]
dropping '{UserHome}/config/plugins' dont solve the problem

**Comment by VISTALL** [comment]
>> dropping '{UserHome}/config/plugins' dont solve the problem

After drop - show please log

**Comment by anton-280** [comment]
Internal error. Please report to https://github.com/consulo/consulo/issues

java.lang.RuntimeException: java.lang.IllegalArgumentException: Missing extension point: com.intellij.applicationLoadListener in area null
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:177)
    at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Missing extension point: com.intellij.applicationLoadListener in area null
    at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:331)
    at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:35)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:110)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
    at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:48)
    at com.intellij.openapi.application.impl.ApplicationImpl.fireBeforeApplicationLoaded(ApplicationImpl.java:564)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:518)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:508)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:169)
    ... 16 more

**Comment by VISTALL** [comment]
U dropped plugin core in 

{Consulo_Home}/plugins/

That why start is failed. Ned reinstall

**Comment by anton-280** [comment]
Solved. Thanks!
