### ISSUE TITLE
java.lang.AbstractMethodError in TemplateCommentPanel

### ISSUE THREAD

**Issue by clumsy** [consulo/consulo#92]
com.maddyhome.idea.copyright.psi.UpdateCopyrightsProvider.createConfigurable(Lcom/intellij/openapi/project/Project;Lcom/maddyhome/idea/copyright/ui/TemplateCommentPanel;Lcom/intellij/openapi/fileTypes/FileType;)Lcom/maddyhome/idea/copyright/ui/TemplateCommentPanel;: com.maddyhome.idea.copyright.psi.UpdateCopyrightsProvider.createConfigurable(Lcom/intellij/openapi/project/Project;Lcom/maddyhome/idea/copyright/ui/TemplateCommentPanel;Lcom/intellij/openapi/fileTypes/FileType;)Lcom/maddyhome/idea/copyright/ui/TemplateCommentPanel;
java.lang.AbstractMethodError: com.maddyhome.idea.copyright.psi.UpdateCopyrightsProvider.createConfigurable(Lcom/intellij/openapi/project/Project;Lcom/maddyhome/idea/copyright/ui/TemplateCommentPanel;Lcom/intellij/openapi/fileTypes/FileType;)Lcom/maddyhome/idea/copyright/ui/TemplateCommentPanel;
	at com.maddyhome.idea.copyright.ui.CopyrightFormattingConfigurable.buildConfigurables(CopyrightFormattingConfigurable.java:116)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:86)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.findConfigurableInGroups(OptionsEditorDialog.java:210)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.findConfigurableInGroups(OptionsEditorDialog.java:223)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.findConfigurableInGroups(OptionsEditorDialog.java:223)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.findLastSavedConfigurable(OptionsEditorDialog.java:203)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.<init>(OptionsEditorDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl._showSettingsDialog(ShowSettingsUtilImpl.java:68)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:53)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:101)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:110)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:188)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:108)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:263)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:254)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:576)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:383)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by VISTALL** [comment]
It was updated API - need download new consulo build. Consulo cant not patch self (

**Comment by clumsy** [comment]
Hm, I've downloaded the latest build (#611), put it my Mac's Applications, started it and get this error each time I go to my Consulo > Preferences.
Do you mean I need to remove it first from my Applications?
It's just it looks to me that some of my previous settings are not compatible with the new code, but I'm not sure.

Is there an issue regarding this problem?

**Comment by VISTALL** [comment]
I think u have **new consulo build** and **old plugins**

Try update **C#**/**XML** plugins (if installed **Java** update too)

**Comment by clumsy** [comment]
Sounds like a bug to me. I don't think IDE should stop providing it's basic functions (like Preferences) even if there's a buggy plugin installed. It could just disable it I guess.
I'll look into the issue nevertheless.

**Comment by VISTALL** [comment]
Main problem - you used night builds.

It was a rewrite of copyright support. It was big change(it changed api, and implementation in plugins).

U have new consulo build, with new copyright support, and have old language plugins.

It tried to call new methods - when he(plugin) known only old implementation.

There no checks between Consulo <-> plugins build versions. Sometimes u can get problems with it, until release.

**Comment by clumsy** [comment]
Do you think it should result in IDE Fatal errors though? Disabling plugin is more starlight-forward if you as me...
